### ISSUE TITLE
KANBAN BOARD: SETUP

### ISSUE THREAD

**Issue by Donmark2k** [Johnadibe/tour-reservation-app-api#23]
In this team, we are 4 in number,

- @Johnadibe 
- @mrprotocoll 
- @Hassaanjbaig-code 
- @Donmark2k 

This is the link to our github [project](https://github.com/users/Johnadibe/projects/4/views/1)

![image](https://github.com/Johnadibe/tour-reservation-app-api/assets/105445428/3bbb4553-a77e-4ba6-966f-acbdeb8cec9e)

![image](https://github.com/Johnadibe/tour-reservation-app-api/assets/105445428/41701758-ee3a-47ba-8450-66a399cead15)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- equitable distribution of tasks 👍 
- All project features seem to be covered 👍 
- All issues have descriptions and weights 👍 
-

## Optional suggestions
- [OPTIONAL] Consider adding labels to your issues, it makes it easier to filter by different types and gives another added level of differentiation among tasks (front-end vs back-end etc.)

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
